
version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: assms_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: assmsdb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d assmsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: